version: '3.8'
services:
  db:
    container_name: db
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=Student
      - MYSQL_USER=kali
      - MYSQL_PASSWORD=kali
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  php-apache-environment:
    # image: php:8.2-apache
    container_name: php-apache
    volumes:
      - "./:/var/www/html"
    build:
        context: ./
        dockerfile: Dockerfile
    depends_on:
        - db
    ports:
      - 80:80
      - 443:443